source "https://rubygems.org"
gemspec 

 gem "jekyll-paginate"
 gem "jekyll-sitemap"
 gem "jekyll-gist"
 gem "jekyll-feed"
 gem "jekyll-include-cache"
 gem "jekyll-coffeescript"
 gem "jekyll-default-layout"
 gem "jekyll-github-metadata"
 gem "jekyll-optional-front-matter"
 gem "jekyll-readme-index"
 gem "jekyll-titles-from-headings"
 gem "jekyll-relative-links"
gem "webrick", "~> 1.7"
